### ISSUE TITLE
json-yup does not work with server-side rendering

### ISSUE THREAD

**Issue by ost-ing** [shipwell/json-yup#3]
Hello,

Thanks for this library.

I am attempting to integrate it into a NextJS SSR application, and get an error that `window` is undefined:

```
ReferenceError: window is not defined
```

It would be cool if this library could be rendered on the server, any chance of supporting this?

**Comment by jctobey** [comment]
Hi Oliver,

Thank you for your interest in json-yup! We don't currently have plans to support server side rendering within the json-yup library, but pull requests are very welcome!

Thanks,
James
