### ISSUE TITLE
Validation issues with `yup 0.32.11`

### ISSUE THREAD

**Issue by ost-ing** [shipwell/json-yup#4]
Hello,

After upgrading to `yup 0.32.11` from `yup 0.29.3` I have numerous issues when validating my applications form.
I'm wondering if this compatibility has been tested yet?

Kind regards,

**Comment by jctobey** [comment]
Good afternoon,

We don't actively maintain this project to ensure compatibility with updated version of dependencies. However, we do welcome pull requests to this repo if you do figure out a solution!
